language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
before_install:
  cpanm -n Devel::Cover::Report::Coveralls
install:
  - perl Makefile.PL
  - make manifest
script:
  - cover -test -report coveralls -make 'make disttest'
